name: django-app

type: "python:3.12"

dependencies:
    python:
        pip: ">=23.0.0"

build:
    flavor: none

hooks:
    build: |
        pip install -r requirements.txt

    post_deploy: |
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput

web:
    commands:
        start: gunicorn Blog.wsgi:application --bind 0.0.0.0:$PORT

    locations:
        "/":
            root: "static"
            passthru: true
        "/media":
            root: "media"
            allow: true

mounts:
    "/media": "shared:files"

disk: 2048
