name: app
type: python:3.11
disk: 512

mounts:
  '/media': 'shared:files/media' 

relationships:
  database: 'db:postgresql'

hooks:
  build: |
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
  deploy: |
    python manage.py migrate --noinput

web:
  locations:
    '/':
      root: ''
      passthru: true
    '/static':
      root: 'staticfiles'
      expires: 1h
    '/media':
      root: 'media'
      expires: 1h