name: app
type: python:3.11
disk: 512

relationships:
  database: 'db:postgresql'

hooks:
  build: |
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
  deploy: |
    python manage.py migrate --noinput

web:
  commands:
    start: "gunicorn Blog.wsgi:application --bind 0.0.0.0:$PORT"