name: inkstack

type: "python:3.12.7"

hooks:
    build: |
        ppip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_remote.txt

        mkdir logs
        python manage.py collectstatic
        rm -rf logs

    post_deploy: |
        python manage.py migrate 

web:
    commands:
        start: gunicorn Blog.wsgi:application --bind 0.0.0.0:$PORT

    locations:
        "/":
            root: "static"
            passthru: true
        "/media":
            root: "media"
            allow: true

mounts:
    "/media": "shared:files"

disk: 2048
