name: app
type: python:3.11
web:
  commands:
    start: gunicorn Blog.wsgi:application --workers 2
  mounts:
    "/static":
      source: local
      source_path: staticfiles
hooks:
  build: |
    python manage.py collectstatic --noinput
dependencies:
  python:
    django: "5.1"
disk: 1024