name: "ll_project"
type: "python:3.10"
source:
    root: "Blog"

relationships:
    database: "db:postgresql"

web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET Blog.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true
        "/media":
            root: "media"
            expires: 1h
            allow: true

disk: 512

mounts:
    "media":
        source: local
        source_path: media
    "static":
        source: local
        source_path: static
    "logs":
        source: local
        source_path: logs

hooks:
    build: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_remote.txt
        mkdir -p static media logs
        python manage.py collectstatic --noinput
    deploy: |
        python manage.py migrate --noinput