name: app
type: python:3.11
disk: 512

mounts:
  '/media': 'shared:files/media'
  '/staticfiles': 'shared:files/static'

relationships:
  database: 'db:postgresql'

hooks:
  build: |
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
  deploy: |
    python manage.py migrate --noinput

web:
  upstream:
    socket_family: unix
  commands:
    start: "gunicorn Blog.wsgi:application --bind 0.0.0.0:$PORT"
  locations:
    '/':
      passthru: true
    '/static':
      root: 'staticfiles'
      expires: 1h
    '/media':
      root: 'media'
      expires: 1h